# Generated by Django 3.2.3 on 2022-03-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='send_on',
            field=models.DateTimeField(),
        ),
    ]
