# Generated by Django 3.2.3 on 2022-04-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_messages_send_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
