# Generated by Django 3.2.3 on 2022-04-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220403_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='user_2',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='friends',
            name='close_friend',
            field=models.BooleanField(default=False),
        ),
    ]
